added tasks from the third block
js-tasks-ru/jsbasic-20201214_darelin13 pull request #5
Opened 2020-12-25 20:55 UTC by niobito

2020-12-25 21:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Переведите текст вида border-left-width в borderLeftWidth
- должна преобразовать 'background-color'
- должна преобразовать 'list-style-image' 
- должна оставить пустую строку без изменений 
- должна преобразовать '-webkit-transition'
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив ��мён
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Функция showSalary(users, age)
+ для пользователей до 40 лет должна вывести строку с зарплатами
+ для пользователей до 30 лет должна вывести строку с зарплатами
```

2020-12-25 21:32 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'list-style-image' 
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-26 17:29 UTC, SinimaWath requested changes

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return arr.filter(number => number >= min && number <= max);
Давай не забудем про отступ от переменных

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  const max = b >= a ? b : a;
Интересное решение!

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(user=> user.name);
Давай сделаем через дестркуторизацию, которую показывал на лекции

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return arr.join('');
Давай сразу возвращать, без промежуточной переменной

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/3-task/index.js
> +    return index ? `${item[0].toUpperCase()}${item.slice(1)}` : item;
Давай для практики, напишем стрелочную функцию без return :)

2020-12-26 17:29 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .map(user => `${user.name}, ${user.balance}`)
Давай дестркуторизацию и сразу использовать name и balance

2020-12-26 18:42 UTC, niobito commented on 3-module/3-task/index.js
> +    return index ? `${item[0].toUpperCase()}${item.slice(1)}` : item;
здесь очень длинная строка получается, смотрится не очень.

2020-12-26 20:39 UTC, niobito commented on 3-module/2-task/index.js
> +  return arr.filter(number => number >= min && number <= max);
done

2020-12-26 20:39 UTC, niobito commented on 3-module/2-task/index.js
> +  const max = b >= a ? b : a;
спасибо)

2020-12-26 20:39 UTC, niobito commented on 3-module/1-task/index.js
> +  return users.map(user=> user.name);
done

2020-12-26 20:39 UTC, niobito commented on 3-module/3-task/index.js
> +  return arr.join('');
done

2020-12-26 20:40 UTC, niobito commented on 3-module/3-task/index.js
> +    return index ? `${item[0].toUpperCase()}${item.slice(1)}` : item;
done

2020-12-26 20:40 UTC, niobito commented on 3-module/4-task/index.js
> +    .map(user => `${user.name}, ${user.balance}`)
done

2020-12-26 20:46 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать 'background-color'
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'list-style-image' 
+ должна оставить пустую строку без изменений 
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Найти min/max в строке
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
+ 25,-1,-234,4,   1000
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-26 21:04 UTC, SinimaWath approved these changes

2020-12-26 21:05 UTC, merged